[build-system]
requires = ["setuptools>=42.0.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "napari_tiledb_bioimg/_version.py"

[tool.isort]
profile = "black"
